# Application
parking.free-minutes-threshold=1
spring.application.name=parking-calculator
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/parking_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
# SQL Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# Server
server.port=8080
# Logging configuration
logging.level.com.paymeter.parking_calculator=INFO
logging.level.root=WARN
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.engine.QueryParameters=OFF
logging.level.org.hibernate.engine.query.HQLQueryPlan=OFF
logging.level.org.springframework.jdbc=OFF
logging.level.org.springframework.transaction=OFF
logging.level.org.springframework.orm=OFF
logging.level.com.zaxxer.hikari=OFF
# Exceptions
server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always
# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.version=1.0.0
# Custom OpenAPI info
springdoc.api-docs.info.title=Parking Calculator API
springdoc.api-docs.info.description=API for calculating parking prices with different discount rules
springdoc.api-docs.info.version=1.0.0
springdoc.api-docs.info.contact.name=API Support
springdoc.api-docs.info.contact.email=support@paymeter.com